theme: jekyll-theme-cayman
repo_base_url: https://github.com/foodcoopshop
repo_url: https://github.com/foodcoopshop/foodcoopshop
title: FoodCoopShop
online_docs_repo_url: https://github.com/foodcoopshop/foodcoopshop.github.io