remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: dark
aux_links:
    "FoodCoopShop on GitHub":
      - "https://github.com/foodcoopshop/foodcoopshop"
repo_url: https://github.com/foodcoopshop/foodcoopshop
title: FoodCoopShop
