remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "FoodCoopShop on GitHub":
      - "https://github.com/foodcoopshop/foodcoopshop"
repo_url: https://github.com/foodcoopshop/foodcoopshop
title: FoodCoopShop
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: yellow
  new:
    title: New in v3.6 (Summer 2023)
    color: #719f41
callouts_opacity: 0.3